env:
  browser: true
  es2021: true
extends: 
  - eslint:recommended
  - plugin:jest-dom/recommended
  - plugin:testing-library/dom
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
plugins:
  - testing-library
  - jest-dom
